exp_name: exp1
checkpoints_dir: ./checkpoints/${exp_name}/${dataset.dataset_name}

hydra:
  run:
    dir: ./checkpoints/${exp_name}/${dataset.dataset_name}/test/

defaults:
  - _self_
  - dataset: HumanML3D

preprocess:
  padding: true
  use_kinematic: true

model:
  motion_encoder: vit_base_patch16_224_in21k
  text_encoder: distilbert-base-uncased

train:
  part_weight: 0.3
  batch_size: 256
  patch_size: 16

eval:
  eval_train: false
  use_best_model: true
  part_enhanced: true